runtime: python310
entrypoint: gunicorn -b :$PORT server:app

handlers:
- url: /
  static_files: build/index.html
  upload: build/index.html

- url: /(.*)
  static_files: build/\1
  upload: build/(.*)

- url: /api/(.*)
  script: auto

- url: /public/(.*)
  static_files: public/\1
  upload: public/(.*)